// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/*";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/_404.tsx": {
    id: "routes/_404";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/_404": typeof import("./app/routes/_404.tsx");
};